(()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data};
let state={variables:[],sourceId:'',taskId:'',batches:[],presetId:'',replica:null},routes=[],sources=[],busy=false,fileUrl='',lastJobs=[];
try{Object.assign(state,JSON.parse(localStorage.getItem('replica:draft:v1')||'{}'))}catch{}
function message(text,error=false){$('status').className='message'+(error?' error':'');$('status').textContent=text}
function save(){if(location.pathname==='/presets')return;const fields={};for(const el of document.querySelectorAll('input[id],select[id],textarea[id]'))if(el.type!=='file')fields[el.id]=el.type==='checkbox'?el.checked:el.value;state.fields=fields;try{localStorage.setItem('replica:draft:v1',JSON.stringify(state))}catch{message('草稿缓存已满，请先保存模板到我的预设。',true)}}
function enabled(){const has=!!state.replica;for(const id of ['manual','referenceVideo','sourceHistory'])$(id).disabled=busy;$('analyze').disabled=busy||!state.sourceId;$('deleteSource').disabled=busy||!state.sourceId;for(const id of ['trial','savePreset','previewPrompts'])$(id).disabled=busy||!has;$('bulk').disabled=busy||!has||!($('trialAccepted').checked||$('skipTrial').checked)}
function clearApproval(){state.pending=null; $('trialAccepted').checked=false;$('skipTrial').checked=false;enabled();save() }
function variables(){ $('variables').innerHTML=state.variables.map((v,i)=>`<div class="variable"><div class="row"><input data-variable="key" data-index="${i}" value="${esc(v.key)}" placeholder="字段名"><input data-variable="label" data-index="${i}" value="${esc(v.label)}" placeholder="显示名称"><button data-remove="${i}" class="secondary" aria-label="删除变量">×</button></div><textarea data-variable="values" data-index="${i}" rows="3" placeholder="每行一个候选值">${esc(v.values.join('\n'))}</textarea></div>`).join('');$('variables').querySelectorAll('[data-variable]').forEach(el=>el.oninput=()=>{const v=state.variables[el.dataset.index];v[el.dataset.variable]=el.dataset.variable==='values'?el.value.split('\n'):el.value;clearApproval()});$('variables').querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{state.variables.splice(Number(el.dataset.remove),1);variables();clearApproval()}) }
function setTemplate(replica,name){state.replica=replica;state.variables=structuredClone(replica.variables||[]);$('templateEditor').hidden=false;$('editorEmpty').hidden=true;$('templateName').value=name||'我的复刻模板';$('fixedRules').value=(replica.fixedRules||[]).join('\n');$('promptTemplate').value=replica.template;$('beats').value=JSON.stringify(replica.beats||[],null,2);$('analysisSummary').textContent=[replica.summary,...(replica.observations||[]),...(replica.uncertainties||[]).map(x=>'待确认：'+x)].filter(Boolean).join('；');$('templateState').textContent='可编辑 · 未验证';variables();enabled();save()}
function readTemplate(){return {...state.replica,template:$('promptTemplate').value,variables:state.variables,fixedRules:$('fixedRules').value.split('\n').filter(Boolean),beats:JSON.parse($('beats').value||'[]')}}
function input(count){return {name:$('templateName').value,replica:readTemplate(),count,duration:Number($('duration').value),ratio:$('ratio').value,resolution:$('resolution').value,videoRoute:$('videoRoute').value,referenceImageIds:[...document.querySelectorAll('[data-reference]:checked')].map(e=>e.dataset.reference),presetId:state.presetId}}
function renderSources(){ $('sourceHistory').innerHTML='<option value="">已保存的参考记录</option>'+sources.map(s=>`<option value="${s.id}">${esc(s.name)} · ${s.duration.toFixed(1)}秒</option>`).join('');$('sourceHistory').value=state.sourceId;const source=sources.find(s=>s.id===state.sourceId);$('frames').innerHTML=source?source.frames.map(f=>`<div><img src="${f.url}" loading="lazy" alt="参考 ${f.time.toFixed(1)}秒"><small>${f.time.toFixed(1)}秒</small></div>`).join(''):'';enabled() }
function timing(){const route=routes.find(r=>r.id===$('videoRoute').value);if(!route)return;const previous=Number($('duration').value)||Math.round(sources.find(s=>s.id===state.sourceId)?.duration||15);const values=route.duration.values?.filter(v=>v<=15)||Array.from({length:Math.min(15,route.duration.max)-route.duration.min+1},(_,i)=>route.duration.min+i);$('duration').innerHTML=values.map(v=>`<option value="${v}">${v}秒</option>`).join('');$('duration').value=values.reduce((a,b)=>Math.abs(a-previous)<=Math.abs(b-previous)?a:b);$('resolution').innerHTML=route.resolutions.map(v=>`<option>${esc(v)}</option>`).join('');$('routeHint').textContent=route.referenceMode==='reference-image'?'支持勾选图片，图片将随提示词提交。':'此模型仅接收提示词，请取消参考图。' }
async function pollAnalysis(){if(!state.taskId)return;try{const task=await api('/replica-analysis/'+state.taskId);if(task.status==='running'){busy=true;enabled();message('正在分析关键帧并提炼可复用模板，可以切换页面。');setTimeout(pollAnalysis,1800);return}state.taskId='';busy=false;if(task.status==='error')throw Error(task.error);setTemplate(task.result,sources.find(s=>s.id===state.sourceId)?.name.replace(/\.[^.]+$/,'')+' · 复刻');message('模板已提炼。请核对事实与替换字段，再预览提示词或生成试片。');enabled();save()}catch(e){busy=false;enabled();message(e.message,true);if(state.taskId)setTimeout(pollAnalysis,5000);save()} }
const event=(target,name,timeout=15000)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{clean();reject(Error('视频解码超时，请使用浏览器支持的MP4/H.264视频'))},timeout);const clean=()=>{clearTimeout(timer);target.removeEventListener(name,done);target.removeEventListener('error',fail)};const done=()=>{clean();resolve()},fail=()=>{clean();reject(Error('视频格式无法解码，请转为MP4/H.264'))};target.addEventListener(name,done,{once:true});target.addEventListener('error',fail,{once:true})});
$('referenceVideo').onchange=async()=>{const file=$('referenceVideo').files[0];if(!file)return;busy=true;enabled();try{if(file.size>300*1024*1024)throw Error('参考视频请控制在300MB以内');const video=$('sourcePlayer');if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl=URL.createObjectURL(file);const metadata=event(video,'loadedmetadata');video.src=fileUrl;video.hidden=false;await metadata;if(!Number.isFinite(video.duration)||video.duration>180)throw Error('请使用180秒以内的视频');video.pause();const canvas=document.createElement('canvas');canvas.width=Math.min(640,video.videoWidth);canvas.height=Math.round(video.videoHeight*canvas.width/video.videoWidth);const context=canvas.getContext('2d'),frames=[];for(let i=0;i<12;i++){message(`本机正在提取关键帧 ${i+1}/12…`);const time=Math.max(.001,video.duration*(i+.1)/12),seek=event(video,'seeked');video.currentTime=time;await seek;context.drawImage(video,0,0,canvas.width,canvas.height);frames.push({time,dataUrl:canvas.toDataURL('image/jpeg',.55)})}const source=await api('/replica-sources',{method:'POST',body:JSON.stringify({name:file.name,duration:video.duration,width:video.videoWidth,height:video.videoHeight,frames})});state.sourceId=source.id;sources.unshift(source);renderSources();clearApproval();message('关键帧已保存在本机，点击分析后才会调用分析模型。')}catch(e){message(e.message,true)}finally{busy=false;enabled();save();$('referenceVideo').value=''}};
$('deleteSource').onclick=async()=>{if(!state.sourceId||!confirm('删除本机关键帧记录？已保存的模板与成片会保留。'))return;try{await api('/replica-sources/'+state.sourceId,{method:'DELETE'});sources=sources.filter(s=>s.id!==state.sourceId);state.sourceId='';renderSources();save();message('参考记录已删除。')}catch(e){message(e.message,true)}};
$('sourceHistory').onchange=()=>{state.sourceId=$('sourceHistory').value;$('sourcePlayer').pause();$('sourcePlayer').hidden=true;renderSources();clearApproval()};
$('analyze').onclick=async()=>{busy=true;enabled();message('已提交分析请求…');try{const task=await api('/replica-analysis',{method:'POST',body:JSON.stringify({sourceId:state.sourceId,direction:$('direction').value,audioNotes:$('audioNotes').value,requestId:crypto.randomUUID()})});state.taskId=task.id;save();pollAnalysis()}catch(e){busy=false;enabled();message(e.message,true)}};
$('manual').onclick=()=>{state.presetId='';state.batches=[];state.references=[];document.querySelectorAll('[data-reference]').forEach(e=>e.checked=false);clearApproval();setTemplate({template:'{{人物}}在{{场景}}完成自然连贯的动作，总时长{{duration}}秒。',fixedRules:['人物为成年人；不改变主体数量','动作自然连贯，保持相同拍摄风格'],variables:[{key:'人物',label:'人物外观',values:['成年女性，黑色长发，修身红色连衣裙']},{key:'场景',label:'场景',values:['简洁明亮的门店入口']}],beats:[],summary:'手动创建的可复用模板',uncertainties:[]},'新复刻模板')};
$('addVariable').onclick=()=>{state.variables.push({key:'字段'+(state.variables.length+1),label:'新字段',values:['请填写候选值']});variables();clearApproval()};
document.addEventListener('workbench:collect-prompt-drafts',event=>{if(!$('promptTemplate').value.trim())return;event.detail.items=[{id:'replica-template',prompt:$('promptTemplate').value}];event.detail.context={fixedRules:$('fixedRules').value,variables:state.variables,beats:$('beats').value};event.detail.apply=rewrites=>{$('promptTemplate').value=rewrites[0].prompt;state.pending=null;clearApproval();save();$('previewPrompts').click()}});
$('previewPrompts').onclick=async()=>{try{const data=await api('/replica-preview',{method:'POST',body:JSON.stringify(input(Number($('count').value)))});$('promptPreview').innerHTML=`<p class="hint">${data.prompts.length}条 · ${data.combinations}种组合${data.repeated?' · 超出组合数量的条目仅更换随机种子':''}</p>`+data.prompts.map((p,i)=>`<details ${i===0?'open':''}><summary>提示词 ${i+1}</summary><div class="preview-prompt">${esc(p.prompt)}</div></details>`).join('');message('提示词已预览，尚未提交视频生成。')}catch(e){message(e.message,true)}};
async function generate(count,trial){if(state.pending&&state.pending.trial!==trial){message('请重试原来的生成按钮，或修改设置取消待提交请求。',true);return}busy=true;enabled();message('正在提交'+(trial?'试片':'批次')+'，请勿重复点击…');try{state.pending=state.pending||{requestId:crypto.randomUUID(),input:input(count),trial};save();const batch=await api('/replica-batches',{method:'POST',body:JSON.stringify({...state.pending.input,requestId:state.pending.requestId})});state.batches.unshift({id:batch.id,trial:state.pending.trial,signature:JSON.stringify({...state.pending.input,count:1})});state.pending=null;save();message('已进入现有生成队列，任务将在成片区域持续显示。');await refreshJobs()}catch(e){message(e.message+'。点击同一生成按钮将重试原提交；修改模板可取消待提交请求。',true)}finally{busy=false;enabled();save()}}
$('trial').onclick=()=>generate(1,true);$('bulk').onclick=()=>generate(Number($('count').value),false);
$('savePreset').onclick=async()=>{try{const preset=await api('/replica-presets',{method:'POST',body:JSON.stringify({id:state.presetId||undefined,name:$('templateName').value,replica:readTemplate(),settings:{videoRoute:$('videoRoute').value,duration:Number($('duration').value),resolution:$('resolution').value,ratio:$('ratio').value,referenceImageIds:state.references||[]}})});state.presetId=preset.id;save();message('已保存到我的预设，可再次编辑或创建批次。')}catch(e){message(e.message,true)}};
async function refreshJobs(){if(!state.batches.length)return;try{const batches=await Promise.all(state.batches.slice(0,10).map(async b=>({batch:b,jobs:await api('/jobs?batch='+b.id)})));lastJobs=batches;$('results').innerHTML=batches.flatMap(({batch,jobs})=>jobs.map(j=>`<article class="result"><b>${batch.trial?'试片':'批次'} · ${j.index}</b><p>${esc(({queued:'排队中',submitting:'正在提交',waiting:'生成中',complete:'已完成',failed:'失败',needs_review:'待确认'})[j.status]||j.status)}</p>${j.error?`<p>${esc(j.error)}</p>`:''}${j.status==='complete'&&j.outputs?.length?`<button data-preview="${j.id}" class="secondary">预览成片</button><a href="/api/video/${j.id}?download=1" class="button secondary" download>下载MP4</a>`:''}</article>`)).join('');document.querySelectorAll('[data-preview]').forEach(el=>el.onclick=()=>window.WorkbenchUI.preview('/api/video/'+el.dataset.preview,'video'));let signature='';try{signature=JSON.stringify(input(1))}catch{}const trialDone=batches.some(b=>b.batch.trial&&b.batch.signature===signature&&b.jobs.some(j=>j.status==='complete'));$('trialAccepted').disabled=!trialDone;if(!trialDone)$('trialAccepted').checked=false;enabled();$('downloadBatch').disabled=!batches.some(b=>b.jobs.length&&b.jobs.every(j=>j.status==='complete'));}catch(e){message(e.message,true)}}
$('downloadBatch').onclick=async()=>{const ready=lastJobs.find(b=>b.jobs.length&&b.jobs.every(j=>j.status==='complete'));if(!ready)return;const id=ready.batch.id;try{await api('/batches/'+id+'/download',{method:'POST',body:'{}'});$('downloadBatch').disabled=true;const poll=async()=>{try{const d=await api('/batches/'+id+'/download');$('downloadBatch').textContent=`准备下载 ${d.complete}/${d.total}`;if(d.ready){const a=document.createElement('a');a.href='/api/batches/'+id+'/archive';a.download='';a.click();$('downloadBatch').textContent='下载本批次 ZIP';$('downloadBatch').disabled=false}else if(d.errors?.length&&!d.running){message(d.errors[0].message,true);$('downloadBatch').disabled=false}else setTimeout(poll,2000)}catch(e){message(e.message,true);$('downloadBatch').disabled=false}};poll()}catch(e){message(e.message,true)}};
async function presets(){const data=await api('/workspace-state');$('clonePage').hidden=true;$('presetsPage').hidden=false;$('pageTitle').textContent='我的预设，随时复用';const render=()=>{$('presetCards').innerHTML=data.presets.filter(p=>p.name.toLowerCase().includes($('presetSearch').value.toLowerCase())).map(p=>`<article class="preset-card"><b>${esc(p.name)}</b><p>${p.kind==='replica'?'复刻模板 · '+(p.replica.variables?.length||0)+'个可替换字段':'生成设置预设'}</p><p>${esc(p.replica?.summary||'保留原有生成页面的设置与模板选择')}</p><button data-use="${p.id}">编辑 / 使用</button> ${p.kind==='replica'?`<a href="/clone?preset=${p.id}&batch=1" class="button secondary">批量创建</a>`:''}<button class="secondary" data-delete="${p.id}">删除</button></article>`).join('')||'<div class="empty">暂无预设，先添加模板或保存复刻结果。</div>';document.querySelectorAll('[data-use]').forEach(el=>el.onclick=()=>{const p=data.presets.find(p=>p.id===el.dataset.use);if(p.kind==='replica')location.href='/clone?preset='+p.id;else{sessionStorage.setItem('workbench:pending-preset',JSON.stringify(p));location.href=p.page}});document.querySelectorAll('[data-delete]').forEach(el=>el.onclick=async()=>{if(!confirm('删除这个预设？已有视频保留。'))return;try{await api('/workspace-presets/'+el.dataset.delete,{method:'DELETE'});data.presets=data.presets.filter(p=>p.id!==el.dataset.delete);render()}catch(e){message(e.message,true)}})};$('presetSearch').oninput=render;render()}
document.addEventListener('input',e=>{if(e.target.type==='file')return;if(['promptTemplate','fixedRules','beats','direction','audioNotes','count','templateName'].includes(e.target.id)){state.pending=null;clearApproval()}save()});$('trialAccepted').onchange=$('skipTrial').onchange=()=>{enabled();save()};$('videoRoute').onchange=()=>{timing();state.pending=null;clearApproval()};$('duration').onchange=$('ratio').onchange=$('resolution').onchange=()=>{state.pending=null;clearApproval()};
(async()=>{try{if(location.pathname==='/presets'){await presets();return}const [provider,sourceList,refs]=await Promise.all([api('/provider'),api('/replica-sources'),api('/references')]);$('analysisModel').textContent='分析：'+(provider.textProvider||'')+' · '+(provider.sceneAnalysisModel||'未配置');routes=provider.routes.filter(r=>r.configured);sources=sourceList;$('videoRoute').innerHTML=routes.map(r=>`<option value="${r.id}">${esc(r.name+' · '+r.model)}</option>`).join('');for(const [id,value]of Object.entries(state.fields||{})){const el=$(id);if(!el||el.type==='file')continue;if(el.type==='checkbox')el.checked=value;else el.value=value}if(!$('videoRoute').value&&routes.length)$('videoRoute').value=routes[0].id;timing();for(const id of ['duration','resolution'])if([...$(id).options].some(o=>o.value===state.fields?.[id]))$(id).value=state.fields[id];renderSources();const selected=new Set(state.references||[]);$('imageChoices').innerHTML=refs.map(r=>`<label><input type="checkbox" data-reference="${r.id}" ${selected.has(r.id)?'checked':''}><img src="${r.previewUrl||'/api/references/'+r.id+'/image'}" loading="lazy" alt="参考图">${esc(r.name)}</label>`).join('');$('imageChoices').onchange=e=>{if(document.querySelectorAll('[data-reference]:checked').length>3){e.target.checked=false;message('最多选择3张参考图',true)}state.references=[...document.querySelectorAll('[data-reference]:checked')].map(e=>e.dataset.reference);state.pending=null;clearApproval()};const presetId=new URLSearchParams(location.search).get('preset');if(presetId){const data=await api('/workspace-state'),preset=data.presets.find(p=>p.id===presetId&&p.kind==='replica');if(!preset)throw Error('复刻预设不存在');state.presetId=preset.id;state.batches=[];state.pending=null;setTemplate(preset.replica,preset.name);const settings=preset.settings||{};if(routes.some(r=>r.id===settings.videoRoute))$('videoRoute').value=settings.videoRoute;timing();for(const id of ['duration','resolution','ratio'])if(settings[id]!==undefined&&[...$(id).options].some(o=>o.value===String(settings[id])))$(id).value=settings[id];state.references=settings.referenceImageIds||[];document.querySelectorAll('[data-reference]').forEach(el=>el.checked=state.references.includes(el.dataset.reference));clearApproval();message('预设已加载，可修改候选值、试片或勾选直接批量生成。')}else if(new URLSearchParams(location.search).has('new'))$('manual').click();else if(state.replica){const f=state.fields||{},v=structuredClone(state.variables);setTemplate(state.replica,f.templateName);state.variables=v;variables();for(const id of ['fixedRules','promptTemplate','beats'])if(f[id]!==undefined)$(id).value=f[id];save()}if(state.taskId)pollAnalysis();refreshJobs();setInterval(refreshJobs,4000);enabled()}catch(e){message(e.message,true)}})();
window.addEventListener('pagehide',save);
})();
