(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=t=>{const ms=Math.round(t*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`};
function cues(text,duration){const lines=text.split('\n').map(s=>s.trim()).filter(Boolean);if(!lines.length)throw Error('请填写字幕，每行一句');if(lines.length>100)throw Error('字幕最多100句');return lines.map((line,i)=>{const timed=/^\[(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)\]\s*(.+)$/.exec(line);const start=timed?Number(timed[1]):duration*i/lines.length,end=timed?Number(timed[2]):duration*(i+1)/lines.length,content=timed?timed[3]:line;if(!Number.isFinite(duration)||duration<=0||start<0||end<=start||end>duration+.1||content.length>300)throw Error('字幕时间或句子长度无效');return {start,end,text:content}})}
const download=(blob,name)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)};
function open(jobId){
 const modal=document.createElement('dialog');modal.style.cssText='width:860px;max-width:95vw;max-height:92vh;border:1px solid #d8ddd3;border-radius:12px;padding:22px;color:#262e24';
 const key='story:subtitles:'+jobId;let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
 modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><h2 style="font-size:18px">短剧字幕 · 成片渲染</h2><button data-close class="btn alt">关闭</button></div><p style="font-size:12px;color:#777">字幕在本机渲染，保留原声音。可选已下载的视频或使用本机缓存，不会自动下载远程成片。</p><div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:18px"><section><div style="position:relative;background:#161616"><video controls preload="none" style="width:100%;max-height:360px"></video><div data-overlay style="position:absolute;bottom:14%;left:6%;right:6%;text-align:center;pointer-events:none;white-space:pre-wrap;color:white;text-shadow:1px 1px 2px black;font-size:20px"></div></div><label style="display:block;margin-top:12px">导入本机视频<input data-file type="file" accept="video/*"></label><button data-cache class="btn alt" style="margin-top:10px">使用已保存的成片</button></section><section><label style="font-size:12px">字幕文本（每行一句，可写 [0-3] 字幕）</label><textarea data-text rows="10" style="width:100%;margin-top:8px">${esc(saved.text||'')}</textarea><div style="display:flex;gap:8px;margin-top:10px"><label>字体大小<input data-size type="number" min="16" max="64" value="${Number(saved.size)||32}"></label><label>底部留白 %<input data-bottom type="number" min="5" max="30" value="${Number(saved.bottom)||14}"></label></div><div style="display:flex;gap:8px;margin-top:14px"><button data-srt class="btn alt">导出 SRT</button><button data-render class="btn">渲染并下载成片</button></div><p data-status role="status" style="font-size:12px;line-height:1.8">可逐句修改字幕与时间，草稿自动保存在本机。</p></section></div>`;
 document.body.appendChild(modal);modal.showModal();const q=s=>modal.querySelector('[data-'+s+']'),video=modal.querySelector('video');let url='',rendering=false,recorder,frame=0,context,stream,audioSource;
 const status=t=>q('status').textContent=t;const persist=()=>{try{localStorage.setItem(key,JSON.stringify({text:q('text').value,size:q('size').value,bottom:q('bottom').value}))}catch{status('字幕草稿缓存已满，请导出SRT保存')}};
 const update=()=>{q('overlay').style.bottom=Number(q('bottom').value)+'%';q('overlay').style.fontSize=Math.round(Number(q('size').value)*video.clientWidth/Math.min(video.videoWidth||720,720))+'px';try{q('overlay').textContent=cues(q('text').value,video.duration).find(c=>c.start<=video.currentTime&&c.end>video.currentTime)?.text||''}catch{q('overlay').textContent=''}};video.ontimeupdate=update;for(const el of [q('text'),q('size'),q('bottom')])el.oninput=()=>{persist();update()};
 const close=()=>{if(rendering){status('渲染中，请等待完成。');return}modal.close()};q('close').onclick=close;modal.addEventListener('cancel',e=>{if(rendering)e.preventDefault()});modal.addEventListener('close',()=>{video.pause();video.removeAttribute('src');video.load();if(url)URL.revokeObjectURL(url);cancelAnimationFrame(frame);context?.close();modal.remove()});
 q('file').onchange=()=>{const file=q('file').files[0];if(!file)return;if(file.size>300*1024*1024){status('请使用300MB以内的本机视频');return}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);video.src=url;status('视频已在本机加载。字幕按句数平均分配，也可以手动指定时间。')};
 q('cache').onclick=async()=>{try{q('cache').disabled=true;status('正在检查本机成片缓存…');const r=await fetch('/api/video-local/'+jobId);if(!r.ok){const data=await r.json();throw Error(data.error)}const blob=await r.blob();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);video.src=url;status('已加载本机缓存视频。')}catch(e){status(e.message)}finally{q('cache').disabled=false}};
 q('srt').onclick=()=>{try{const data=cues(q('text').value,video.duration);download(new Blob([data.map((c,i)=>`${i+1}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n')],{type:'text/plain;charset=utf-8'}),'短剧字幕-'+jobId+'.srt');persist()}catch(e){status(e.message)}};
 q('render').onclick=async()=>{let chunks=[],failure='';try{
  if(!video.src||!Number.isFinite(video.duration)||video.duration>120)throw Error('请先加载120秒以内的视频');const data=cues(q('text').value,video.duration),size=Number(q('size').value),bottom=Number(q('bottom').value);if(size<16||size>64||bottom<5||bottom>30)throw Error('字体大小应为16–64，底部留白为5–30%');
  if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw Error('当前浏览器不支持本机字幕渲染，请使用新版Edge或桌面工作台');
  const mime=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('浏览器没有可用的视频编码器');
  rendering=true;q('render').disabled=true;q('cache').disabled=true;q('file').disabled=true;q('text').disabled=true;q('size').disabled=true;q('bottom').disabled=true;video.controls=false;video.pause();
  await new Promise((resolve,reject)=>{if(video.currentTime<.02){resolve();return}const timer=setTimeout(()=>reject(Error('视频定位超时')),10000);video.addEventListener('seeked',()=>{clearTimeout(timer);resolve()},{once:true});video.currentTime=0});
  const canvas=document.createElement('canvas');canvas.width=Math.min(video.videoWidth,720);canvas.height=Math.round(video.videoHeight*canvas.width/video.videoWidth);const g=canvas.getContext('2d');stream=canvas.captureStream(25);
  context=context||new AudioContext();await context.resume();audioSource=audioSource||context.createMediaElementSource(video);audioSource.disconnect();const destination=context.createMediaStreamDestination();audioSource.connect(destination);audioSource.connect(context.destination);for(const track of destination.stream.getAudioTracks())stream.addTrack(track);
  recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:3500000});let bytes=0;recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>150*1024*1024){failure='成片超过150MB，请缩短视频或降低尺寸';video.pause();if(recorder.state==='recording')recorder.stop()}}};
  const done=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=e=>reject(Error(e.error?.message||'视频编码失败'))});
  const draw=()=>{g.drawImage(video,0,0,canvas.width,canvas.height);const subtitle=data.find(c=>c.start<=video.currentTime&&c.end>video.currentTime);if(subtitle){g.font=`600 ${size}px "Microsoft YaHei",sans-serif`;g.textAlign='center';g.lineJoin='round';g.lineWidth=Math.max(2,size/10);g.strokeStyle='rgba(0,0,0,.85)';g.fillStyle='white';const lines=[];let line='';for(const char of subtitle.text){if(g.measureText(line+char).width>canvas.width*.88&&line){lines.push(line);line=''}line+=char}if(line)lines.push(line);const base=canvas.height*(1-bottom/100)-(lines.length-1)*size*1.25;lines.forEach((l,i)=>{g.strokeText(l,canvas.width/2,base+i*size*1.25);g.fillText(l,canvas.width/2,base+i*size*1.25)})}status(`本机正在渲染 ${Math.round(video.currentTime/video.duration*100)}% · 请保持本页可见`);if(rendering)frame=requestAnimationFrame(draw)};
  video.onended=()=>{cancelAnimationFrame(frame);if(recorder.state==='recording')recorder.stop()};video.onerror=()=>{failure='视频解码失败';if(recorder.state==='recording')recorder.stop()};recorder.start(1000);draw();await video.play();await done;if(failure)throw Error(failure);download(new Blob(chunks,{type:mime.split(';')[0]}),'短剧字幕成片-'+jobId+(mime.startsWith('video/mp4')?'.mp4':'.webm'));status('字幕成片已渲染并下载，原视频与音频保持在成片中。');persist();
 }catch(e){status('渲染失败：'+e.message)}finally{rendering=false;cancelAnimationFrame(frame);video.pause();if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());audioSource?.disconnect();if(context)await context.suspend();video.controls=true;video.onended=null;q('render').disabled=false;q('cache').disabled=false;q('file').disabled=false;q('text').disabled=false;q('size').disabled=false;q('bottom').disabled=false}}

}
function enhance(){const jobs=document.getElementById('jobs');if(!jobs)return;for(const a of jobs.querySelectorAll('a[href^="/api/video/"][download]')){const card=a.closest('.job');if(!card||card.querySelector('[data-subtitles]'))continue;const id=/\/api\/video\/([a-f0-9-]{36})/.exec(a.getAttribute('href'))?.[1];if(!id)continue;const button=document.createElement('button');button.className='btn alt';button.textContent='字幕渲染';button.dataset.subtitles=id;button.onclick=()=>open(id);card.appendChild(button)}}
function ready(){const jobs=document.getElementById('jobs');if(jobs){new MutationObserver(enhance).observe(jobs,{childList:true,subtree:true});enhance()}const section=document.querySelector('.headline');if(section){const button=document.createElement('button');button.className='btn alt';button.textContent='字幕渲染';button.onclick=()=>open('local');section.appendChild(button)}}
window.StorySubtitles={open,cues,stamp};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
