(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=t=>{const ms=Math.round(t*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`};
function cues(text,duration){const lines=text.split('\n').map(s=>s.trim()).filter(Boolean);if(!lines.length)throw Error('请填写字幕，每行一句');if(lines.length>100)throw Error('字幕最多100句');return lines.map((line,i)=>{const timed=/^\[(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)\]\s*(.+)$/.exec(line);const start=timed?Number(timed[1]):duration*i/lines.length,end=timed?Number(timed[2]):duration*(i+1)/lines.length,content=timed?timed[3]:line;if(!Number.isFinite(duration)||duration<=0||start<0||end<=start||end>duration+.1||content.length>300)throw Error('字幕时间或句子长度无效');return {start,end,text:content}})}
const api=async(url,options={})=>{const r=await fetch('/api'+url,options);const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;};
const download=(blob,name)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};
function open(jobId){
 const modal=document.createElement('dialog');modal.style.cssText='width:880px;max-width:95vw;max-height:92vh;border:1px solid #d8ddd3;border-radius:12px;padding:22px;color:#262e24';
 const key='story:subtitles:'+jobId;let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
 modal.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><h2 style="font-size:18px">短剧字幕 · 成片渲染</h2><button data-close class="btn alt">关闭</button></div><p style="font-size:12px;color:#777">字幕在本机处理，保留原声音，成片自动保存。渲染期间可以关闭窗口，回来查看进度与下载。</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:18px"><section><div style="position:relative;background:#161616"><video controls playsinline preload="metadata" style="width:100%;max-height:360px"></video><div data-overlay style="position:absolute;bottom:14%;left:6%;right:6%;text-align:center;pointer-events:none;white-space:pre-wrap;color:white;text-shadow:1px 1px 2px black;font-size:20px"></div></div><label style="display:block;margin-top:12px">导入本机视频<input data-file type="file" accept="video/*"></label><button data-cache class="btn alt" style="margin-top:10px" ${jobId==='local'?'hidden':''}>保存并加载原成片</button></section><section><label>字幕文本（每行一句，可写 [0-3] 字幕）</label><textarea data-text rows="8" style="width:100%;margin-top:8px">${esc(saved.text||'')}</textarea><div style="display:flex;gap:8px;margin-top:10px"><label>字体大小<input data-size type="number" min="16" max="64" value="${Number(saved.size)||32}"></label><label>底部留白 %<input data-bottom type="number" min="5" max="30" value="${Number(saved.bottom)||14}"></label></div><div class="wb-toolbar" style="margin-top:14px"><button data-srt class="btn alt">导出 SRT</button><button data-render class="btn">渲染并保存 MP4</button></div><p data-status role="status" style="font-size:12px;line-height:1.8">正在加载原成片…</p><progress data-progress hidden style="width:100%" max="100"></progress></section></div><section data-result hidden style="margin-top:16px"><h3>已保存的字幕成片</h3><video data-output controls playsinline preload="metadata" style="width:100%;max-height:360px"></video><p><a data-download class="btn" download>下载字幕 MP4</a></p></section>`;
 document.body.appendChild(modal);modal.showModal();const q=s=>modal.querySelector('[data-'+s+']'),video=modal.querySelector('video');let objectUrl='',file=null,timer,taskId='',preparing=false;
 const status=t=>q('status').textContent=t,persist=()=>{try{localStorage.setItem(key,JSON.stringify({text:q('text').value,size:q('size').value,bottom:q('bottom').value}))}catch{}};
 const update=()=>{q('overlay').style.bottom=Number(q('bottom').value)+'%';q('overlay').style.fontSize=Math.round(Number(q('size').value)*video.clientWidth/720)+'px';try{q('overlay').textContent=cues(q('text').value,video.duration).find(c=>c.start<=video.currentTime&&c.end>video.currentTime)?.text||''}catch{q('overlay').textContent=''}};
 video.ontimeupdate=update;video.onloadedmetadata=()=>{if(!taskId)status(`原成片已加载 · ${video.duration.toFixed(1)} 秒，可以预览并编辑字幕。`);update();};video.onerror=()=>status('原成片加载失败，请点击“保存并加载原成片”重试，或导入本机视频。');for(const el of [q('text'),q('size'),q('bottom')])el.oninput=()=>{persist();update();};
 q('close').onclick=()=>modal.close();modal.addEventListener('close',()=>{clearTimeout(timer);for(const v of modal.querySelectorAll('video')){v.pause();v.removeAttribute('src');v.load();}if(objectUrl)URL.revokeObjectURL(objectUrl);modal.remove();});
 q('file').onchange=()=>{file=q('file').files[0];if(!file)return;if(file.size>300*1024*1024){file=null;status('请使用300MB以内的本机视频');return;}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);video.src=objectUrl;};
 async function poll(task){if(!modal.open)return;taskId=task.id;const active=['queued','saving','rendering'].includes(task.status);q('render').disabled=active;q('progress').hidden=!active;q('progress').value=task.progress||0;
  if(task.status==='complete'){q('result').hidden=false;const src='/api/subtitle-renders/'+task.id+'/video';if(q('output').getAttribute('src')!==src)q('output').src=src;q('download').href=src+'?download=1';status('字幕 MP4 已保存到本机。请预览，或点击下方下载按钮。');return;}
  if(task.status==='error'){status('渲染失败：'+task.error+'；可修改后重新渲染。');return;}
  status(task.status==='saving'?'正在保存原成片，保存完成后开始渲染…':task.status==='queued'?'渲染任务已保存，等待执行…':`本机正在渲染 ${task.progress||0}% · 可以关闭窗口，稍后回来下载`);
  timer=setTimeout(async()=>{try{await poll(await api('/subtitle-renders/'+taskId));}catch(e){status(e.message);q('render').disabled=false;}},1000);
 }
 q('cache').onclick=async()=>{try{preparing=true;q('cache').disabled=true;let state=await api('/video/'+jobId+'/cache',{method:'POST'});while(!state.ready){if(!modal.open)return;if(state.error)throw Error(state.error);status(`正在保存原成片 ${(state.bytes/1048576).toFixed(1)}${state.totalBytes?' / '+(state.totalBytes/1048576).toFixed(1):''} MB…`);await new Promise(resolve=>setTimeout(resolve,1000));state=await api('/video/'+jobId+'/cache');}file=null;video.src='/api/video-local/'+jobId;}catch(e){status(e.message);}finally{preparing=false;q('cache').disabled=false;}};
 q('srt').onclick=()=>{try{const data=cues(q('text').value,video.duration);download(new Blob([data.map((c,i)=>`${i+1}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n')],{type:'text/plain;charset=utf-8'}),'短剧字幕-'+jobId+'.srt');persist();status('SRT 字幕已准备下载。');}catch(e){status(e.message);}};
 q('render').onclick=async()=>{try{if(preparing)throw Error('原成片正在保存，请稍候');if(!Number.isFinite(video.duration)||video.duration<=0||video.duration>120)throw Error('请先加载120秒以内的视频');cues(q('text').value,video.duration);q('render').disabled=true;persist();let uploadId;if(file){status('正在导入本机视频…');uploadId=(await api('/subtitle-uploads',{method:'POST',body:file})).id;}const input={jobId:file?'local':jobId,uploadId,text:q('text').value,size:Number(q('size').value),bottom:Number(q('bottom').value),duration:video.duration,width:video.videoWidth,height:video.videoHeight};clearTimeout(timer);q('result').hidden=true;await poll(await api('/subtitle-renders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}));}catch(e){status(e.message);q('render').disabled=false;}};
 if(jobId!=='local')video.src='/api/video/'+jobId+'?preview=1';else status('请导入本机视频，再填写字幕。');
 api('/subtitle-renders?jobId='+jobId).then(data=>{if(data.task&&modal.open)poll(data.task);}).catch(e=>status(e.message));
}
function enhance(){const jobs=document.getElementById('jobs');if(!jobs)return;for(const a of jobs.querySelectorAll('a[href^="/api/video/"][download]')){const card=a.closest('.job');if(!card||card.querySelector('[data-subtitles]'))continue;const id=/\/api\/video\/([a-f0-9-]{36})/.exec(a.getAttribute('href'))?.[1];if(!id)continue;const button=document.createElement('button');button.className='btn alt';button.textContent='字幕渲染';button.dataset.subtitles=id;button.onclick=()=>open(id);card.appendChild(button);}}
function ready(){const jobs=document.getElementById('jobs');if(jobs){new MutationObserver(enhance).observe(jobs,{childList:true,subtree:true});enhance();}const section=document.querySelector('.headline');if(section){const button=document.createElement('button');button.className='btn alt';button.textContent='字幕渲染';button.onclick=()=>open('local');section.appendChild(button);}}
window.StorySubtitles={open,cues,stamp};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
