import {readSecret} from './secrets.js';
// Text/vision only: video submit/poll continues through the existing Wan adapter.
export function createTokenDanceChat({apiKey=readSecret('TOKENDANCE'),fetchImpl=fetch,maxConcurrent=Number(process.env.TOKENDANCE_CHAT_MAX_CONCURRENT)||3}={}){
 const base=process.env.TOKENDANCE_CHAT_BASE_URL||'https://tokendance.space/gateway/v1';
 const pending=[],times=[];let active=0,timer;const perMinute=Math.max(1,Number(process.env.TOKENDANCE_CHAT_REQUESTS_PER_MINUTE)||30);
 const pump=()=>{if(timer){clearTimeout(timer);timer=null}while(times.length&&times[0]<Date.now()-60000)times.shift();while(times.length<perMinute&&active<Math.max(1,Math.min(8,maxConcurrent))&&pending.length){const item=pending.shift();active++;times.push(Date.now());Promise.resolve().then(item.run).then(item.resolve,item.reject).finally(()=>{active--;pump()})}if(pending.length&&times.length>=perMinute)timer=setTimeout(pump,Math.max(50,times[0]+60000-Date.now()))};
 return {name:'TokenDance',configured:Boolean(apiKey),promptModel:process.env.TOKENDANCE_PROMPT_MODEL||'qwen3.5-flash',sceneAnalysisModel:process.env.TOKENDANCE_VISION_MODEL||'qwen3-vl-plus',
 requestChat(payload,timeoutMs=120000){return new Promise((resolve,reject)=>{pending.push({resolve,reject,run:async()=>{if(!apiKey)throw Error('TokenDance 未配置密钥');let response;try{response=await fetchImpl(base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(timeoutMs)})}catch(cause){const error=Error(cause.name==='TimeoutError'?'TokenDance 文本/视觉请求超时':'无法连接 TokenDance 文本/视觉接口');error.transient=true;throw error}let data;try{data=await response.json()}catch{throw Error('TokenDance 返回了非JSON响应')}if(!response.ok||data.error){const message=String(data.error?.message||data.message||'请求失败').replace(/sk-[A-Za-z0-9_-]+/g,'[已隐藏密钥]').slice(0,400);const error=Error('TokenDance：'+message);error.status=response.status;error.transient=response.status===429||response.status>=500;error.retryAfterMs=(Number(response.headers.get('retry-after'))||0)*1000;throw error}return data}});pump()})}
 };
}
